### ISSUE TITLE
slacken `Bom.serialNumber` in data models

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-php-library#277]
Currently, the `Bom` data model's setter of `serialNumber` asserts a certain format.
This format is the one from JSON schema. This format is also allowed via XSD. 
Unfortunately, there is an alternative format allowed in the XSD.

Currently, the normalizer will normalize any `serialNumber`.
But according to the schema, it must follow a certain format.

Therefore, the format must not be checked in the setter, but asserted by the normalizer.
Invalid serial numbers should be omitted on normalization, but are allowed in the model.

Additionally, it might help if a `serialNumber` generator was provided by the library.
Luckily, this was already done here:
see https://github.com/CycloneDX/cyclonedx-php-composer/blob/204cb909ddeb24c4eeb5be0a0eae34217402d059/src/MakeBom/Builder.php#L402-L416

**Comment by llaville** [comment]
Hello @jkowalleck

Because I wanted to implement the serialNumber feature, I have a look on the new release 2.1.0 and found perharps a typo error !
Still present in master branch https://github.com/CycloneDX/cyclonedx-php-library/blob/master/phpmd.xml#L26
And introduced by commit https://github.com/CycloneDX/cyclonedx-php-library/commit/dc61f08b99dc117e0c3899a2105c1d2afe0d726d#diff-86663aeec12838bb61855e163b38da1d1e38d18276b2d25c9dd6761127914a43R26

It identify class `CycloneDX\Core\Utils\BomUtil`, while only `CycloneDX\Core\Utils\BomUtility` class exists.

**Comment by jkowalleck** [comment]
thanks for spotting this.
Will have it fixed ASAP.
